= Notes

Use `default` for default constructors to initialize with all default values instead of junk.

Use safe casts instead of C-style round-bracketed cast which is unsafe.

Never ever write `using` statements in a header file.

Use {cpp} scoped enums instead of C-style enums.

In modern {cpp} the only preprocessor you'll probably need is `include`.

Use references and smart pointers instead of C-style pointers.

Declare references that you use to prevent a copy but do not want to change the original instance, as `const&` i.e. const references.

Declare member functions as `const` to make sure that they do not change the member variable.

If you are not enabling compiler optimizations, use inline functions.

Avoid calling code that has side effect in the condition clause of statement with boolean/logical operators.

Always do a check to ensure that denominator is non-zero when doing division.

For readability do not use shift operators in place of arithmetic operators when performing multiplication/division by 2.

To provide access to a private member, public getter should be your first choice.
Use friend if and only if you think adding a public getter is going to unnecessarily expose the variable to the whole world when in fact it is required by only one class.

While using templates, if a particular operator doesn't make sense for the data type that you want to use in the template, then do template specialization instead of implementing the operator in the data type.