== Overview

{cpp} is a powerful language and many people stop after learning the basics.
They continue to write it like one of the languages that they are already familiar with instead of using more advanced parts of the language and STL.

Modern {cpp} is:

* Expressive: you can choose keywords and constructs that suit specific needs.
For example, a range-based for loop used to iterate over a collection expresses the intent to the reader more clearly than other methods.

* Feature-rich: Lambdas, templates, const, smart pointers, stl classes, and all other features makes you more productive and gives you a host of benefits.
So don't use {cpp} as C with classes

* Readable: Easy to understand.
Don't make optimizations, go for readability of the code.
The modern compiler is powerful enough to make the optimizations much better than what you can write.

* written using stack semantics: you would rarely need raw pointers and manually memory management.
Almost all code uses objects on the stack some of which maybe smart pointers that encapsulates raw pointers.

{cpp} standard library is not the biggest standard library when compared to other languages, however it is growing.

[NOTE]
====
You don't need to force yourself to use every single modern feature, but make it a point to not ignore the modern feature when it is right solution for your problem.
====

== STL Containers
Containers that are already implemented in the STL is a great alternative to C-style arrays to manage collections.

* There are a lot of varieties of containers catering to different needs.
* Huge number of methods to handle various needs.
* They know their size and manage themselves hence they are less error-prone.
* Throws exceptions when you do something invalid.
* They work very well with the STL algorithms.
* You don't have to manage memory, they manage it themselves, and they work well with smart pointers.
* Type safety prevents you from accidentally putting invalid type into your collection
* Very expressive, meaning those who read the code will right away know what exactly the code is doing

=== `vector`
`vector` should be your goto container.

[TIP]
====
If you are not sure, use `vector`.
====

It starts with a size 1 and as you add more elements it doubles in size and grows itself.
This type of growing requires vector to use memory on heap.
But as it cleans up after itself, we don't really need to worry about that.

It stores everything in consecutive memory locations.
Hence, indexing and random access is very fast.
You can traverse using iterators or do random access via `[]`.
All this makes vector high performance.

But, if the vector holds objects, then while growing the vector will require making new copies to push into the array and destroying old copies in the old array.
This will incur performance cost.

So vector's performance depends on how you use it, and what you store in it.

=== `array`
`array` can be seen as `vector` that never grows.
As `array` size is known in compile-time it is stored on stack.

=== `list`
`list` is a linked list.
Hence, each element knows where to find the next one.
So, elements are not required to be stored in contiguous locations.
Hence, when you add an element in the middle you don't need to move around all other elements, only the element preceding it (and probably succeeding it, if it's a doubly linked list) will need to be updated to point to it.

Hence, this efficient in memory but traversing and indexing is expensive.
Sorting is even more expensive as you'll need to change everyone's pointers.

[TIP]
====
Even if you think you need `list`, start with `vector` and check the performance and then go for the `list`.
A huge majority of the `list` APIs are same as `vector`.
Hence, a lot of the code will work unchanged by simply renaming a `vector` variable as `list`.
====

=== Other collections

* Other popular dynamic collections
** `map` is kept sorted and keys must be unique
*** `unordered_map` will not sort keys, hence faster insertion
** `multimap` allows collisions
*** `unordered_multimap` to have unsorted keys

* Some more collections
** `stack`
** `queue`
** `dequeue`
** `priority_queue`

To discover more go to https://en.cppreference.com/w/cpp/container[here].

== Lambda

A lambda is an expression that holds code to do something.
This can be stored in a variable and passed to another function.
[TIP]
====
The type of lambda is very complicated to write, so better use `auto`.
====

* This is required for generic work.
* Used widely in functional programming style and concurrency.

The compiler generates a class. from the lambda definition, containing 3 parts:

* Capture clause: class member variables
* Parameters: class method parameters
* Function body: class method body

From the lambda execution compiler generates code to instantiate the class and call the method.

=== Is lambda really required?

Whatever a lambda does, the same can be done by function objects(functors) or functions passed to function pointers.
Function pointers are difficult to read, and write and the functions that are passed to it are implemented elsewhere.

But lambdas are easy to understand, and they keep the code where it is used.
As all code is kept in place:

* Code is clean and easy to read
* It is easier to express the intent
* You can have the confidence to change it as no-one else will use this

Considering all the benefits above, we can forget about functors, and function pointers, and use lambda.
Though lambda didn't introduce anything new in terms of capability to the language, it made the capabilities more accessible.

=== Parts of a lambda

==== The capture

When you want something from the calling scope to be accessible within the lambda, you need to use the capture clause to capture it.
You can capture by:

* value:
+
Now just like pass by value, a copy of the variable is made during the time of capture.
This internal copy has nothing to do with the original variable and the same copy will be used any number of times that you execute the lambda, even after the original variable has gone out of scope.
Unless the keyword `mutable` is used, this internal copy cannot be changed by the code within the lambda as well.
Hence, by default, the variables that were capture by copy behave as `const` within the lambda.

* reference:
+
Now no copy is made, and you can modify the target variable.
However, there is a possibility to have dangling references, for example, when you have passed the lambda to another thread and the reference in the thread where reference was captured has gone out of scope.
+
Here, as no copy is made, and we cannot re-initialize references anyway, hence `mutable` is irrelevant.

* alias
+
`[a=y + 1]`

* move
+
`[std::move(b)]` is used when you have the potential for a dangling reference.

Even when you tell the lambda to capture everything in the calling scope by value or reference, the compiler generates code capturing only whatever you are using in the lambda.

[TIP]
====
Just capture everything by value/reference in the capture clause, and then list whatever you want to do otherwise.
====

If you are not putting the lambda into a variable, then capture it by value/reference based on the size of the object you are capturing.

If you are storing the lambda in a variable and passing it elsewhere, and if there's a potential for dangling reference, then capture by value.

==== return

Lambdas may return a value.

The type of return can normally be inferred by the compiler.
Sometimes, they cannot, for example, when you return `int` in one place and `double` in another place within the lambda.
In such cases the developer needs to specify.
In the given example, the developer will need to specify the return type as `double` by doing:
----
[...](...) -> double { ... }
----

Whenever the lambda is passed as a predicate its return type must match the type that is expected by whoever executes it, in other words, whoever executes it will impose the return type.

==== Parameters

Lambdas take the parameter from whoever executes it.
Hence, the parameter type must match the type given by whoever executes it, in other words, whoever executes it will impose the parameter type.

== STL Algorithms

Not everything that you want to do with a container is a member function of that very container.
Several things that you normally want to do on a container is located in another part of the standard library.

For example, you cannot find a method to locate an element in a `vector` in its public definitions.
The ability to find an element is present in `<algorithm>` which contains a lot of templates, which can work on any containers.
When you use one of the classes from `<algorithm>` and pass your `vector` to it, you get the functionality you are looking for.

To connect `<algorithm>` and container, iterators are used.
Iterators are mistakenly confused with pointers by a lot of developers, and they shy away from it.
But, in reality iterators not only helps to interface the containers and algorithms but also helps write safe code.

[NOTE]
====
This kind of separation between containers, iterators, and algorithms in STL makes room for countless number of permutations, and combinations between them.
Hence, a vast array of features can be obtained without bloating the containers.
====

When you use STL containers, iterators, and algorithms, you can eliminate a lot of messy loops and decision-making statements and continue/break.
Also, different people write these in different ways.
For example, some may use iterators instead of `[]` for iterating.
All these makes it necessary that you spend time to understand even simple things.

Very often you can write everything you want to do in a single/few line(s) using a function, with a clear name, from the STL algorithms.
Hence, nobody will need to read the whole loop to understand what you are doing, the code becomes very clear, readable and expresses the intent very well.
Moreover, STL is well tested for edge cases and highly optimized for performance.
Hence, it is probably better than what you would write.
[TIP]
====
When you are using verbs such as find, sort, generate, remove etc. it is highly likely that an STL algorithm implementation for it already exists.
====

Using STL algorithms prevents you from making subtle mistakes such as iterating over the very container that you are modifying either via indexing or an iterator.

[IMPORTANT]
====
Stop writing raw loops, and figure out the STL algorithm.
====

Most STL algorithms work with most iterators.
Hence, even if you change your container, all your algorithms still work.

To search for available methods go https://en.cppreference.com/w/cpp/algorithm[here].
For more learning on STL algorithms you can do this https://app.pluralsight.com/library/courses/beautiful-cplusplus-stl-algorithms/[course].
