== Intro

Many developers use STL not so much for a variety of reasons.
But in reality, there isn't a trade-off to be made.
By using STL your code is more readable, reliable, efficient, expressive, and fast.

== STL Philosophy and Approach

{cpp} standard library(STL) is not the biggest when compared to other languages.
However, it is growing, and most of the things currently in STL is severely under-utilised.

Don't be shy to delegate things to STL.
If you need something, its most likely to be there.

Not everything is a member function.
There is a huge preference for free functions in the STL coz they split up the code of collections(for example: `<vector>`), from the code that works on these collections(for example: `<algorithm>`).
`<iterator>` contains code that acts as the interface between the two.

Hence, STL is divided into collections, algorithms, iterators.
This kind of separation in STL makes room for countless number of permutations, and combinations between them.
Hence, a vast array of features can be obtained without bloating the containers.

=== `<algorithm>`
Works on the whole container of any type(`vector` etc. or even `string` can be used as a container) or a range inside it, no matter what type of data(`int` etc. or any class that you write) that it contains.

All this works through `iterator`.
They are not pointers.

If you ever feel the need to write a raw loop, there's almost certainly a better way to write it using STL.
STL is well tested for edge cases and highly optimized for performance.
Hence, it is probably better than what you would write.

With use of STL nobody will need to read the whole loop to understand what you are doing, the code becomes very clear, readable and expresses the intent very well.
In other words, why have 8-10 lines of code that require a comment when you could just have a single line of code that documents itself.

=== Some headers to know
Working with collections: `algorithm`

Collections: `vector`, `array`, `list`, `stack`, `map`, `queue`,
[NOTE]
====
you can treat `string` as a collection of `char`
====

Gain particular functionality: `iterator`

Pairs: `utility`

Tuple: `tuple`

Certain calculations: `numeric`

Complex numbers: `complex`

Math oriented such as trigonometry: `cmath`

Regular expression: `regex`

Time-related: `chrono`

Smart pointers: `memory`

=== Using member or non-member functions for `begin` and `end`
If an STL collection contains `begin` and `end` as its member functions, then the non-member functions `begin` and `end` in STL will return the member function version.

The non-member function versions work with not just STL containers but also C-style arrays as well.
When used with C-style array they know to automatically calculate the beginning and the end addresses.

You can write a function that accepts iterators and works on your collection.
To this function, you can use non-member function version of `begin` and `end` even if your collection itself doesn't have member functions `begin`, and `end`.

Considering all the benefits, use the non-member functions `begin` and `end`.

== Glossary

=== Counting and Finding

* `count`: how many target values are present in the collection?

* `count_if`: how many values in the collection meet a particular condition?

* `all_of`: does all the values in the collection meet a particular condition?

* `none_of`: does none of the values in the collection meet a particular condition?

* `any_of`: does any of the values in the collection meet a particular condition?

* `find`: get the iterator of the first occurrence of the target value in a collection
+
[IMPORTANT]
====
Here, first doesn't mean the first from the beginning of the collection.
First means the first one starting from the iterator that you passed into the collection as `begin`.
====
+
[NOTE]
====
If your search failed you get `end`
====

* `find_if`:  get the iterator of the first element in a collection that meets a particular condition

* `find_if_not`:  get the iterator of the first element in a collection that does not meet a particular condition

* `find_first_of`: get the iterator of the first element found in a given collection that also belongs to the search collection

* `search`: get the iterator of the first element of the first occurrence of a (whole) sequence in a collection

* `find_end`: get the iterator of the first element of the last occurrence of a sequence in a collection

* `search_n`: get the iterator of the first occurrence of `n` consecutive instances of the target element in a collection

* `adjacent_find`: get the iterator of the first occurrence of 2 consecutive instances of any element in a collection

=== Sorting

* `sort`: sort a collection in ascending order or as per the lambda
+
[NOTE]
====
The collection's item type should work with operator `<` for `sort` to work.
If not, write a predicate to compare.
====
+
[WARNING]
====
This modifies your collection.
If you don't want that, make a copy, and work on the copy.
====


* `stable_sort`: assumes that a given collection is already sorted, then applies the second sorting rule which tries to maintain the given order as much as possible.
+
[IMPORTANT]
====
If you want to sort, lets say by number and then within the elements that are having same number, you want to sort by name.
In that case, do a regular `sort` by name, and then `stable_sort` by number.
====
+
[WARNING]
====
Use it only to applies a second sub-sorting rule.
Don't use it for everything, this is very slow.
====

* `is_sorted`: is a collection sorted in ascending order or as per the lambda

* `max_element`: get the iterator of the largest item in a collection

* `min_element`: get the iterator of the smallest item in a collection

* `upper_bound`: in a sorted collection, get the iterator to the first element which is greater than the target
+
[WARNING]
====
If you use this with unsorted collection, you'll have unexpected output
====
+
[NOTE]
====
This is very fast as it performs a binary search within the given sorted range using:

----
item < target
----

or the predicate with arguments:

----
(item_type, target_type)
----
====

* `lower_bound`: in a sorted collection, get the iterator to the first element which is not less than the target
+
[NOTE]
====
`lower_bound` looks quite similar to `upper_bound`, but with it get iterator to first element which is greater than or equal to the target instead of just greater than with `upper_bound`.
====
+
[TIP]
====
If your collection is sorted, use `lower_bound` or `upper_bound` to find a value rather than `find` or its related functions.
====

* `shuffle`: shuffle a given collection using a given generator.
+
[TIP]
====
Just use `mt19937` generator, don't think too much.
====
+
[WARNING]
====
Modifies the collection.
====

* `partial_sort`: instead of sorting the whole collection between `begin` and `end`, this sorts the collection between `begin` and `end` until `middle` i.e. this sorts in such a way that after execution, all the elements until the pre-sort position of `middle` are in order and the remaining elements may not be in order.
+
[IMPORTANT]
====
After partial sort everything that comes at and after the pre-sort position of `middle`, will be meet the sorting predicate(by default, be greater than) over the elements that come before the pre-sort position of `middle`.
====
+
[TIP]
====
If the collection is too big, and you need to sort just a few, then this could give a huge boost in performance.
====
+
[NOTE]
====
There is no `stable_partial_sort`.
====

* `is_sorted_until`: to get the iterator of the position in a collection until which the elements are sorted.

* `partial_sort_copy`: do `partial_sort` into another collection without modifying the original collection.
The number of elements partially sorted is the size of the destination collection.
+
[WARNING]
====
If you are creating an empty collection, and to extend it, if you do `reserve`, "partial_sort_copy" doesn't work.
`reserve` internally expands the memory but as the collection is still not filled, `size()` will return 0.
`partial_sort_copy` uses `size()` to figure out how many elements to partially sort.
Therefore, with `reserve`, you'll get `size()` as 0, and `partial_sort_copy` does nothing.
Hence, do not use `reserve` here, use `resize` coz it not only does `reserve` but also fills in the default values.
Now, `size()` will return a non-zero value, and `partial_sort_copy` will do partial sorting.
====

* `nth_element`: to put the `n`^th^ element of a collection with a value that would have occupied that position if the collection was sorted.
+
[IMPORTANT]
====
After running this, only the `n`^th^ element is in order, everything before it is lesser than it but may not be in order and everything after it is greater than it but may not be in order.
====
+
[TIP]
====
Use this for rough partitioning the collection as everyone who are lesser than and everyone who are greater than the pre-sort value at `n`.
====
+
[NOTE]
====
You cannot simply pass the value of `n`, you'll need to provide the iterator for the `n`^th^ position.
====
