== Indirection

As {cpp} is a strongly typed language, even the references and pointers have a type.
They cannot simply point to anything.
They'll need to point to the target type that was mention during declaration.

=== Reference

A reference is an alias for a target variable.
Any action done on the reference is actually being done on the target.
No need of special punctuation to indicate this, it can be just used as if the actual target is being used.

A reference can only be set to a target when declaring it, and it cannot be made to refer to something else.

=== Pointers

Pointers hold the address of the target variable, or it can also hold nothing meaning point to nowhere.
To point to nowhere you can use 0 or the keyword `nullptr`
[TIP]
====
Always use `nullptr` keyword for null pointer.
====

It can be uninitialized, initialized, and reinitialized whenever required.
You should never leave a pointer uninitialized coz it can take a junk value which might get wrongly interpreted as address, and there is no way to check for this.
Hence, if you are yet to initialize your pointer, then initialize it to `nullptr` during declaration.
This way you can do a null check before using the pointer.
[TIP]
====
If you want to make sure that your pointer is never null/invalid, then probably you are better off using a reference.
====

Special punctuation is required to perform action on the target(called dereferencing), otherwise the operation performed will be interpreted as being performed on the address of the target.

== Const

To commit to a compiler that you won't change something:

[WARNING]
====
Make sure to have `const` correctness from the very beginning.
Achieving `const` correctness later is often tedious and difficult.
====

[TIP]
====
Your default way to write all variables, arguments, functions, members etc. should be with `const` until you no longer can.
====

* When declaring a local variable
+
----
int const val = 1.717 // read as "constant integer"
----

* When passing a parameter:

** Pass by value
+
----
int foo(int const b);
----
+
here `b` is copied anyway, so even if it changes, there's no harm to the original value.
however, if you still want to conceptually make sure that the logic doesn't need to make any changes to any parameters, you can do this way.

** Pass by reference
+
----
int foo(int const& b); // read as "constant reference to integer"
----
+
here `b` is reference, hence it is not copied and there is a potential for modification of the original value.
Adding `const` before a reference, will make sure that the original value is never modified via this reference.
+
Reference to a const is not allowed coz the reference unless declared as const should allow the change of target value but if the target value is a const then there's no way that it can be changed.
Therefore, reference to a const is a paradox and hence, it is not allowed.
+
const reference to a const value comes within the above const reference to value as if the reference is constant, then there is no way that you can change it regardless of the target is constant or not.
Hence, we do not have a special case for this.

** Pass by pointer
+
You can pass

*** `const` pointer to a target:
+
----
int foo(int * const b); // read as "constant pointer to integer"
----
+
same logic as const reference.

*** Pointer to `const` target:
+
----
int foo(int const * b); //  read as "pointer to constant integer"
----
+
Here pointer can be reassigned to point to another address but the target that it points to must be a constant.

*** `const` pointer to `const`
+
----
int foo(const int * const b); // read as "constant pointer to constant integer"
----
+
here you cannot change both the pointer and the data that it points to.

* When using a member function:
+
----
int foo() const;
----
+
when you have a member function, it can directly access member variables without passing them as arguments.
If something was passed as argument, then we can use `const` with argument to make sure that it is not modified.
To make sure that member function doesn't modify member variable, we qualify the member function itself as `const`.

=== Style
`const` can be written before or after, for example:
----
const int ci = 3; // const-before style
----
is same as:
----
int const ci = 3; // const-after style
----
for the compiler.

For us, using const-after enhances readability as shown previously, especially when using with pointers.
You just need to read it from lhs to rhs.

The only confusing exception would be "const reference to a target" which is written as:
----
int const & cri = i;
----
instead of:
----
int & const cri = i;
----
But, as "const reference to const target" is covered under "const reference to target", and as there is no "reference to a const target", we don't need to worry about this.
If we remember just this one exception to style, it is good enough.

[TIP]
====
Instead of writing:
----
int const & cri = i;
----
and reading it as reference to const int,
write it as:
----
int const& cri = i;
----
so that you can read `const&` as one word "const-reference" and hence read `int const&` as "const-reference to int".
====

== Memory Management

=== Free store

[NOTE]
====
Stack & local store are used interchangeably.
Similarly, Heap & free store as well.
====

Local variables are allocated memory on stack when they are declared, and this memory is cleared when you return from the function in other words, the scope of the local variable ends.

If you want to store variables beyond the scope of the function in which they are declared:

* Create the variable on the heap, and keep the address to the heap location on the stack.
+
This is automatically done by using `new` operator to instantiate the object.
Now whatever, the constructor does it will be doing it on the heap.
+
[NOTE]
====
Syntax will vary a little when you are doing `new` on raw array.
But, when you are using modern {cpp}, you should never use raw arrays, and use arrays from STL.
====

* When you exit the function, you'll need to make sure that the address to the heap location is returned coz after exit the stack will be cleared, and the address of the heap location currently stored on the stack, will be lost.
+
This is done by having a pointer as the return type.

When you are done, and you do not need it anymore, you can manually call `delete` operator to trigger the destructor and then deallocate all the memory that was allocated on the heap.
[WARNING]
====
The local pointer variable that was used to call `delete` will still contain the address to the deallocated heap location.
So don't forget to reinitialize it to `nullptr` so that null checks can protect you.
If you forget to reinitialize it to `nullptr`, then null checks cannot protect you, and you'll end up, dereferencing an illegal memory location, and reading junk and/or causing code crash.
====
[NOTE]
====
Doing `delete` on `nullptr` doesn't cause code crash.
====

Using `new` and `delete` is a manual way of memory management which is very tedious and error-prone.
There are several error scenarios:

* The local variable which contains the pointer goes out of scope, then you lose access to the object
* Delete too soon meaning dereferencing an invalid pointer
* Delete twice meaning doing delete on an invalid address
* Never delete which will lead to memory leaks
* Someone copies that pointer, and them using that pointer can lead to a host of issues mentioned above.

Thumb rules for manual memory management(called as rule of five):

* Whenever you create an object on heap, keep its pointer inside another object which calls delete, on all the pointers it has been given, in its destructor so that all pointers are cleaned up when it goes out of scope.

* Don't do shallow copies of the object, do deep copies using copy constructor.
This will prevent the copy pointer dereferencing the location after it has been deallocated via the original pointer.

* Overload copy assignment operator to delete existing data and (deep) copy the new data that is being assigned.
When you simply use the assignment operator without overloading it as mentioned above, the current pointer will take in the address of the pointer that is being assigned to it and its own address is lost.
Once the address is lost, you can never free the memory.

* If the resource in an object is expensive, deleting it while deleting the object and recreating it while creating a new object can be expensive.
To avoid this, we can `move` it to another object using move constructor.

* If the resource in an object is expensive, unlike overload copy assignment operator where you delete everything, and (deep) copy, you delete and (deep) copy only the inexpensive part, and you `move` the expensive resource.

Hence, to make manual memory management less error-prone you'll need to write at least five functions some of which are complicated, and you will have to check for things such as self-assignment etc.
All these make manual memory management painful.

So the best solution is:

* use STL as much as possible
* design your class in such a way that you stick to local store as much as possible
* if you still have to use free store:
** Write copy and move to perform proper deep copies
** use a smart pointer

=== Smart Pointers
Smart pointers work their way around the rule of five to give safe memory management.

A smart pointer basically is a template class with following properties:

* Just one member variable `T*`
* Constructor saves a pointer variable in the member variable
* Destructor will `delete` the member variable
* Overload dereference operators(`*` and `->`) to give you the actual pointer
* Does one of the following
** Make copy and move impossible
** Implements copy and move to perform reference counting

==== `unique_ptr`
This has very less overhead, but it is not copiable.
It achieves this by:

* making the copy constructor and copy assignment operator `private`, or
* using `=delete` on copy constructor and copy assignment operator

Hence, you cannot simply assign this pointer to wherever you want.
`std::move` will need to be used to use it at multiple places.
Whenever it goes out of scope, it automatically cleans up heap without leaving any memory leak.

==== `shared_ptr`
This is copiable.
[NOTE]
====
If your design is good there are very rare instances when you'll need to use this.
====
Performs reference counting where each copy increments a counter, each copy that goes out of the scope decrements the counter in its destructor, and if used properly, the last one to go out of scope will have a count zero, and it will clean up the memory.

==== `weak_ptr`
Allows you to read a shared pointer without bumping the reference count.
While `unique_ptr`, and `shared_ptr` makes sure that there is no memory leak, `weak_ptr` cannot do that.

== Indirection and Inheritance

A class that inherits from a class will still have all the capabilities of the base class, hence a  reference or a pointer of the base class can be used with the inherited class.
This is called Liskov substitutability.

The reverse is not possible meaning, you cannot use a pointer or reference of a class with its parent class as some functionality of the class may not be present in its parent.

While using indirection to a class using its parent's reference or pointer, if you execute a function, the function that runs can be the function in the base class or the inherited class based on how they are declared in the base class.
If the function in the base class was declared as `virtual`, the derived class function executes, otherwise the base class function will execute.

[WARNING]
====
If you don't mark the destructor of the base class as virtual, when you point/refer to inherited class using a base class reference or pointer, and delete it, the destructor of only the base class will be called but not the destructor of the inherited class.
If you do not call the destructor of the inherited class, all the additional resources specific to the inherited class that were allocated will never be cleared causing a memory leak.
====
[TIP]
====
As soon as you mark a function of a class as `virtual`, mark its destructor as `virtual` as well.
====

Having a `virtual` function comes with a cost both in terms of memory and runtime performance as a redirection needs to happen which is facilitated by a virtual table.

When you are using a reference or pointer of a class's parent, you cannot call the functions that are present in the class but not present in its parent.

The same rules apply to smart pointers as well.

=== Slicing
One downside to indirection and inheritance is slicing.

A base class may not have all the features of a derived class, hence a base class cannot be copied into derived class.
[IMPORTANT]
====
You can overload the assignment operator to copy the base class into derived class and initialize the additional object in the derived class with some (defaults) values.
But, you don't get this without writing any code.
====
But, derived class has all the properties of the base class, hence you can copy derived class into a base class.
But, you lose access to the extra members in the derived class.
This is called slicing.

Slicing causes memory leak.
Moreover, when this slicing occurs, you even lose the virtual table information.
Hence. when you make a function call, you always get the function call of the base class even if the function is marked as `virtual` in the base class.
Hence, polymorphism is lost.

One simple solution is to not copy the derived class object into the base class object.
But, this is not fully avoidable coz sometimes you may need to pass by value a derived class to a base class parameter in a function call.
As the derived class is passed by value, a copy will be made, as it is passed to a base class parameter, slicing will happen on the copy.

To avoid this issue, use references or pointers when passing a derived class to a function.
[TIP]
====
If you design your code well, you'll almost always not require a base class pointer as a parameter, just the base class reference will suffice.
====
