= Notes

== Overview

{cpp} is a powerful language that's suitable for platforms as small as embedded systems, and as large as servers and clusters.
It delivers tremendous performance, not just fast code, but code that uses less electricity to get the job done.

== Understanding {cpp} in context

Modern {cpp} is way different from older {cpp}.

* Memory management need not be manual
* No need for manual pointer arithmetic
* Looks a lot more like C# or Java but faster

{cpp} doesn't belong to a person or a company.
The https://isocpp.org[standards committee] defines the language and compiler vendors implement their compiler as per this standard.
[IMPORTANT]
====
Backward compatibility is maintained between all versions of the language.
Hence, no need to worry about code compilation when moving to a new version of the language.
====
Different vendors reach 100% compliance at different pace.
The big 3 compilers are GCC, clang, MSVC.
Generally, you don't have to worry about this as most compilers will eventually reach there.
But, it is good to know that this exists.

The https://en.cppreference.com/w/[wiki for {cpp}] lists everything related to the language.

Standard library has a lot of useful classes, collections, smart pointer, and stream IOs etc.

You can find a compiler https://isocpp.org/get-started[here].

== Tools
{cpp} is a general purpose language which can be used to build a variety of applications:

* Embedded and Mobile devices
* Console apps
* Services
* Server apps
* Client apps
* Libraries for all the above

== Variables and Fundamental Types

{cpp} is a strongly-typed language

* Variables can hold only certain types of values
* Variables need to be declared before they are used
* Post declaration variable type cannot be changed

There are fundamental built-in types in the language:

* Numbers
** Integers
+
All integer datatype corresponds to the number of bytes that it can hold.

*** `char`: 1 byte
*** `short`: 2 byte
*** `int`: holds the size of the address bus of the device
+
most efficient type and not standardized for historic reasons
*** `long`: 8 byte
*** `long long`: 16 bytes

+
+
Here the range of numbers that can be held by the integer depends on whether it is signed or unsigned.

*** `signed`: Range: -2^n-1^ to 2^n-1^-1
+
By default, integer type is considered signed.
*** `unsigned`: Range: 0 to 2^n^-1
+
To use unsigned integer type it needs to be explicitly specified using this keyword
** Real numbers
*** float
*** double
* Boolean
** bool
* Single characters
*** When an utf-8 character is enclosed in single quotes, compiler translates the character into its ascii value which is an unsigned 1 byte number which can be stored into `char` type

User defined types using structs and classes.
[NOTE]
====
They are full participants, they can do everything that a fundamental type can do.
====

Sometimes typing the type can be annoying, difficult or even impossible.
Hence, {cpp} has `auto` keyword which forces the compiler to deduce the type for us.
[NOTE]
====
Even if you `auto`, variable is still strongly typed.
====
[TIP]
====
Use it to enhance code readability, for example, in case of ugly iterator declarations, or difficult to figure out lambda types.
====

=== Casting
When we mix types that are incompatible with each other, we might suffer from loss of precision etc.
Hence, we get a compiler warning.
If this is intentionally done, then to tell the compiler to not worry, you can do casting.
[WARNING]
====
Don't simply cast to suppress compiler warnings.
Make sure that you clearly understand what you are doing.
====

Unlike C which uses unsafe round bracketed casts, {cpp} has safe casts(also called as templated casts), always use them.

== User defined types
=== `class`

A `class` can depict the properties and the behavior.
Properties are the data members, and behavior is implemented by the function members.
These members maybe `private`, `protected`, and `public` which determines their visibility to code outside the class.

Unless specified, by default the members are private.

`private` makes sure that code only within the class can access a member.
`public` allows code both inside and outside the class to access a member.
`protected` is like `private` for everyone except the class that inherits the class under consideration.

An object is an instance of a class which is declared like a variable of a fundamental type.

==== Constructor
An object's properties can be initialized using a special function called constructor which has the same name as the class and is executed right after the object creation & before any other code is executed.

The compiler inserts a default constructor that initializes the data members.
The default constructor takes no arguments and hence if the data members are fundamental types they can be filled with junk, and if they are user-defined types such as other class they can call their respective constructor.

You can add your own constructor to initialize the members.
When you add your own constructor, the compiler stops generating the default constructor.
Hence, if you would still like to have a default constructor, you will need to explicitly write one.

Just like any other member functions constructors will also have an access specifier.
Based on how you want to use a particular class, you can determine where to put the constructor.

==== Scope
Variables have a lifetime.
When an object is declared, the constructor is called and the memory is allocated for it.
At the end of the closing brace of the function body that it was created in, its destructor is automatically called, and after destructor runs, the next step is to free the memory used by the object.
Writing a destructor is optional.

[TIP]
====
Resource acquisition is done in constructor, and release is done in destructor.
This way you can never forget to release a particular resource when the object using it no longer exists.
====

==== Building
You'll need to declare it in the header and include it in the source file where you define/implement it.
Keep a class's definition/implementation in a single source file.

=== `struct`
This is same as `class` but here, by default, members are `public` unless specified otherwise.
Conventionally, they are used only to hold data, and as soon as any behavior comes to picture i.e. method, then it is converted into a `class`.

=== `namespace`
They are used to prevent the name collisions between members of classes.
It separates from class name with `::`.

[WARNING]
====
Never write `using` constructs in a header file.
People using your header files, may not want to get your `using` statements
====

=== inheritance

Inheritance is when you derive a new class from another class.
This enables code reuse.

The access specifier of the base class members within the inherited class depends upon the type of inheritance and the visibility of the base class members in their base class.

`private` members are anyway not visible to any code outside the class.
Hence, the inherited class can't see or access the `private` members of the base class.

|====
|Type of Inheritance |Base class access specifier |Access in derived class

.2+|public

|protected
|protected

|public
|public

.2+|protected

|protected
|protected

|public
|protected

.2+|private

|protected
|private

|private
|private

|====

=== `enum`
It is a construct used to associate unique names to a set of constants.
Easy to forget constants, so better to use names under an enumeration.

In {cpp}, even `enum` can be scoped under a class/struct or created as its own `enum class`.
Due to scoping, enums can have a same name associated with their constants.
Hence, you'll need to use fully-qualified names to use them.

In {cpp}, the underlying type of the constants in an enum can be a type other integral type other than `int`.

[TIP]
====
Use scoped enum over C style unscoped enum.
====

=== Preprocessor directives
These are instructions for the preprocessor.
They start with `#`

[WARNING]
====
When used incorrectly, can lead to subtle bugs.
Hence, you need to be very careful when using them.
====

In modern {cpp}, the only thing you'll probably ever need is `#include`.

== Flow control

These statements allow you to control the flow of the program.
Hence, you can perform decision-making and looping.

If there is only one statement under the condition for flow control, then braces can be omitted.
[IMPORTANT]
====
For the sake of readability, use braces.
====

=== Decision-making

`if`(`-else`), `switch`, `goto`, immediate if using ternary operator.

[WARNING]
====
Do not use `goto` it will affect readability and maintainability of your code.
====

Use ternary operator if and only if the code is very short and you can fit in a single line.

==== `switch`
It is a good alternative when you are testing a variable against too many values of integral type or an `enum`(which is in an integer behind the scenes).
`break` is used to prevent fall through.
`default` is used run some code when no conditions are met.

In C++17, you can do:
----
switch(int x = someFunc(); x)
----
this will make sure that `x` goes out of scope when program comes out of the `switch` statement.

=== Looping

`while`, `do-while`, `for`.

`break` and `continue` can be used to exit the current loop or skip the current iteration.

`while` and `for` are a pre-check loops and `do-while` is a post check loop.

`while` to do something as long as a condition is true.
`do-while` do something once and then same as `while`
`for` to do something for a certain number of iterations.
